dd <- hryt
dd$text<-str_replace_all(dd$text,"yapay zeka", "" )
dd$text<-str_replace_all(dd$text,"Yapay zeka", "" )
dd$text<-str_replace_all(dd$text,"e ticaret", "eticaret" )

dd$text<-str_replace_all(dd$text,"$", "ş" )

dd$text<-str_replace_all(dd$text,"&Ouml;", "Ö" )
dd$text<-str_replace_all(dd$text,"&ouml;", "ö" )
dd$text<-str_replace_all(dd$text,"&Ccedil;", "Ç" )
dd$text<-str_replace_all(dd$text,"&ccedil;", "ç" )
dd$text<-str_replace_all(dd$text,"&#286;", "Ğ" )
dd$text<-str_replace_all(dd$text,"&#287;", "ğ" )
dd$text<-str_replace_all(dd$text,"&#304;", "İ" )
dd$text<-str_replace_all(dd$text,"&#305;", "ı" )
dd$text<-str_replace_all(dd$text,"&#350;", "Ş" )
dd$text<-str_replace_all(dd$text,"&#351;", "ş" )
dd$text<-str_replace_all(dd$text,"&Uuml;", "Ü" )
dd$text<-str_replace_all(dd$text,"&uuml;", "ü" )
dd$text<-str_replace_all(dd$text,"&acirc;", "a" )
dd$text<-str_replace_all(dd$text,"&rsquo;", "'" )
dd$text<-str_replace_all(dd$text,"&rdquo;", "'" )
dd$text<-str_replace_all(dd$text,"&lsquo;", "" )
dd$text<-str_replace_all(dd$text,"&ldquo;", "" )
dd$text<-str_replace_all(dd$text,"&nbsp;", "" )
dd$text<-str_replace_all(dd$text,"&gt;", "" )
dd$text<-str_replace_all(dd$text,"&lt;", "" )
dd$text<-str_replace_all(dd$text,"iframe;", " " )
dd$text<-str_replace_all(dd$text,"allowfullscreen", " " )
dd$text<-str_replace_all(dd$text,"height", " " )
dd$text<-str_replace_all(dd$text,"class=\"hr", " " )
dd$text<-str_replace_all(dd$text,"10px", " " )
dd$text<-str_replace_all(dd$text,"background", " " )
dd$text<-str_replace_all(dd$text,"allow", " " )
dd$text<-str_replace_all(dd$text,"autoplay", " " )
dd$text<-str_replace_all(dd$text,"background", " " )
dd$text<-str_replace_all(dd$text,"rjet", " " )
dd$text<-str_replace_all(dd$text,"seperator", " " )
dd$text<-str_replace_all(dd$text,"style=", " " )
dd$text<-str_replace_all(dd$text,"media", " " )
dd$text<-str_replace_all(dd$text,"encrypted", " " )
dd$text<-str_replace_all(dd$text,"style", " " )
dd$text<-str_replace_all(dd$text,"NA", " " )
dd$text<-str_replace_all(dd$text,"#ff017e", " " )
dd$text<-str_replace_all(dd$text,"&loz", " " )
dd$text<-str_replace_all(dd$text,"quot", " " )
dd$text<-str_replace_all(dd$text,"yüzde", " " )

dd$text<-dd$text %>%str_replace_all("bugü", "bugün")
dd$text<-dd$text %>%str_replace_all("ümle", "cümle")
dd$text<-dd$text %>%str_replace_all("çerik", "içerik")
dd$text<-dd$text %>%str_replace_all("nde", "")
dd$text<-dd$text %>%str_replace_all("nda", "")
dd$text<-dd$text %>%str_replace_all("yla", "")
dd$text<-dd$text %>%str_replace_all("com", "")
dd$text<-dd$text %>%str_replace_all("www", "")
dd$text<-dd$text %>%str_replace_all("dan", "")
dd$text<-dd$text %>%str_replace_all("Hürriyet", "")
dd$text<-dd$text %>%str_replace_all("nin", "")
dd$text<-dd$text %>%str_replace_all("doğru", "")
dd$text<-dd$text %>%str_replace_all("dogru", "")
dd$text<-dd$text %>%str_replace_all("arasi", "")
dd$text<-dd$text %>%str_replace_all("arası", "")
dd$text<-dd$text %>%str_replace_all("dedi", "")
dd$text<-dd$text %>%str_replace_all("var", "")
dd$text<-dd$text %>%str_replace_all("embed", "")
dd$text<-dd$text %>%str_replace_all("sh", "")
dd$text<-dd$text %>%str_replace_all("ürriyet", "")
dd$text<-dd$text %>%str_replace_all("i<U+0307>lgi<U+0307>ni<U+0307>zi<U+0307>", "ilgi")
dd$text<-dd$text %>%str_replace_all("bi<U+0307>lgi<U+0307>sayariniz", "bilgisayar")

dd$text<-dd$text %>%str_replace_all("Ä±", "ı")  
dd$text<-dd$text %>%str_replace_all("Ã¼", "ü")
dd$text<-dd$text %>%str_replace_all("Ã¶", "ö")
dd$text<-dd$text %>%str_replace_all("Ã§", "ç")  
dd$text<-dd$text %>%str_replace_all("ÅŸ", "ş")  
dd$text<-dd$text %>%str_replace_all("ÄŸ", "ğ")  

dd$text<-dd$text %>%str_replace_all("ÅŸ", "Ş")
dd$text<-dd$text %>%str_replace_all("Ãœ", "Ü")
dd$text<-dd$text %>%str_replace_all("Ã‡", "Ç")
dd$text<-dd$text %>%str_replace_all("Ã–", "Ö")
dd$text<-dd$text %>%str_replace_all("Ä°", "İ")
dd$text<-dd$text %>%str_replace_all("â", "a")
dd$text<-dd$text %>%str_replace_all("\u0307", "")

dd$text<-dd$text %>%str_replace_all("^\\s*<U\\+\\w+>\\s*", " ")
dd$text<-dd$text %>%str_replace_all("\\b\\w{1,2}\\s", " ")
dd$text<-dd$text %>%str_replace_all("§", " ")
dd$text<-dd$text %>%str_replace_all("Ã", "")
dd$text<-dd$text %>%str_replace_all("ã", "")
dd$text<-dd$text %>%str_replace_all(" *\\b[[:alpha:]]{1,2}\\b *", "")
dd$text<-dd$text %>%str_replace_all("^ +| +$|( ) +", "\\1")


hryt <- dd
remove(dd)








